name: Run benchmarks

on:
  pull_request:

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6
      - uses: julia-actions/julia-buildpkg@latest
      - name: Install dependencies
        # Pin Parsers < 2.0 to fix https://github.com/JuliaData/CSV.jl/issues/868
        run: julia -e 'using Pkg; pkg"add PkgBenchmark BenchmarkCI@0.1 Parsers@1.1.2"'
      - name: Run benchmarks
        run: julia -e '
          using PkgBenchmark, BenchmarkCI;
          BenchmarkCI.judge(
              PkgBenchmark.BenchmarkConfig(
                  env = Dict(
                      "JULIA_NUM_THREADS" => "1",
                      "OMP_NUM_THREADS" => "1",
                  ),
              );
          );'
      - name: Show
        run: julia -e 'using BenchmarkCI; BenchmarkCI.displayjudgement()'
      #- name: Push results
      #  run: julia -e '
      #    using BenchmarkCI;
      #    BenchmarkCI.postjudge();
      #    BenchmarkCI.pushresult(;
      #        url = "git@github.com:Oblynx/HierarchicalTemporalMemory.jl",
      #    );'
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    SSH_KEY: ${{ secrets.DOCUMENTER_KEY }}